-- Seed data: Common aquarium species (~80 for MVP)
-- Full 2,000 species would be populated from a CSV in production

insert into public.species (scientific_name, common_name, category, family, temp_min, temp_max, ph_min, ph_max, max_size_inches, difficulty, aggression, aliases) values

-- FRESHWATER FISH
('Pterophyllum scalare', 'Angelfish', 'freshwater_fish', 'Cichlidae', 75, 82, 6.0, 7.5, 6.0, 'intermediate', 'semi_aggressive', '["angel","freshwater angelfish"]'),
('Paracheirodon innesi', 'Neon Tetra', 'freshwater_fish', 'Characidae', 70, 78, 6.0, 7.0, 1.5, 'beginner', 'peaceful', '["neon","neons"]'),
('Paracheirodon axelrodi', 'Cardinal Tetra', 'freshwater_fish', 'Characidae', 73, 81, 5.5, 7.0, 2.0, 'intermediate', 'peaceful', '["cardinal","cardinals"]'),
('Carassius auratus', 'Goldfish', 'freshwater_fish', 'Cyprinidae', 65, 72, 7.0, 8.0, 12.0, 'beginner', 'peaceful', '["goldfish","fancy goldfish"]'),
('Danio rerio', 'Zebra Danio', 'freshwater_fish', 'Cyprinidae', 65, 77, 6.5, 7.2, 2.5, 'beginner', 'peaceful', '["danio","zebrafish"]'),
('Poecilia reticulata', 'Guppy', 'freshwater_fish', 'Poeciliidae', 72, 82, 7.0, 8.0, 2.5, 'beginner', 'peaceful', '["guppies","fancy guppy","livebearer"]'),
('Xiphophorus hellerii', 'Swordtail', 'freshwater_fish', 'Poeciliidae', 72, 82, 7.0, 8.0, 5.0, 'beginner', 'peaceful', '["swordtails"]'),
('Xiphophorus maculatus', 'Platy', 'freshwater_fish', 'Poeciliidae', 70, 79, 7.0, 8.0, 2.5, 'beginner', 'peaceful', '["platies","sunset platy"]'),
('Poecilia latipinna', 'Sailfin Molly', 'freshwater_fish', 'Poeciliidae', 72, 80, 7.0, 8.0, 5.0, 'beginner', 'peaceful', '["molly","mollies"]'),
('Betta splendens', 'Betta', 'freshwater_fish', 'Osphronemidae', 76, 82, 6.5, 7.5, 3.0, 'beginner', 'aggressive', '["siamese fighting fish","betta fish","bettas"]'),
('Trichogaster trichopterus', 'Three Spot Gourami', 'freshwater_fish', 'Osphronemidae', 72, 82, 6.0, 8.0, 5.0, 'beginner', 'semi_aggressive', '["gourami","blue gourami","opaline gourami"]'),
('Trichogaster lalius', 'Dwarf Gourami', 'freshwater_fish', 'Osphronemidae', 72, 82, 6.0, 7.5, 3.5, 'beginner', 'peaceful', '["dwarf gourami","flame gourami"]'),
('Corydoras paleatus', 'Peppered Cory', 'freshwater_fish', 'Callichthyidae', 70, 78, 6.5, 7.2, 2.5, 'beginner', 'peaceful', '["cory","cories","corydoras","pepper cory"]'),
('Corydoras sterbai', 'Sterbai Cory', 'freshwater_fish', 'Callichthyidae', 73, 82, 6.5, 7.5, 2.5, 'beginner', 'peaceful', '["sterbai","sterba cory"]'),
('Hypostomus plecostomus', 'Common Pleco', 'freshwater_fish', 'Loricariidae', 72, 82, 6.5, 7.5, 18.0, 'beginner', 'peaceful', '["pleco","plecostomus","suckerfish"]'),
('Ancistrus sp.', 'Bristlenose Pleco', 'freshwater_fish', 'Loricariidae', 60, 80, 6.5, 7.5, 5.0, 'beginner', 'peaceful', '["bristlenose","bushy nose pleco","ancistrus"]'),
('Chromobotia macracanthus', 'Clown Loach', 'freshwater_fish', 'Botiidae', 77, 86, 6.0, 7.5, 12.0, 'intermediate', 'peaceful', '["clown loach","loach"]'),
('Botia striata', 'Zebra Loach', 'freshwater_fish', 'Botiidae', 73, 79, 6.5, 7.5, 4.0, 'beginner', 'peaceful', '["candy stripe loach","zebra botia"]'),
('Pterygoplichthys gibbiceps', 'Sailfin Pleco', 'freshwater_fish', 'Loricariidae', 73, 82, 6.5, 7.5, 20.0, 'beginner', 'peaceful', '["leopard pleco","sailfin"]'),
('Astronotus ocellatus', 'Oscar', 'freshwater_fish', 'Cichlidae', 74, 81, 6.0, 8.0, 14.0, 'intermediate', 'aggressive', '["oscar fish","tiger oscar","velvet cichlid"]'),
('Cichlasoma synspilum', 'Redhead Cichlid', 'freshwater_fish', 'Cichlidae', 75, 82, 7.0, 8.0, 12.0, 'intermediate', 'aggressive', '["firemouth","synspilum"]'),
('Microgeophagus ramirezi', 'German Blue Ram', 'freshwater_fish', 'Cichlidae', 78, 85, 6.0, 7.0, 3.0, 'advanced', 'peaceful', '["ram","GBR","blue ram","butterfly cichlid"]'),
('Apistogramma cacatuoides', 'Cockatoo Dwarf Cichlid', 'freshwater_fish', 'Cichlidae', 77, 84, 6.0, 7.2, 3.5, 'intermediate', 'semi_aggressive', '["apisto","cacatuoides"]'),
('Apistogramma agassizii', 'Agassiz Dwarf Cichlid', 'freshwater_fish', 'Cichlidae', 77, 84, 5.5, 7.0, 3.5, 'intermediate', 'semi_aggressive', '["agassizii apisto","apisto"]'),
('Symphysodon discus', 'Discus', 'freshwater_fish', 'Cichlidae', 82, 88, 5.5, 7.0, 7.0, 'advanced', 'peaceful', '["discus fish"]'),
('Carinotetraodon travancoricus', 'Pea Puffer', 'freshwater_fish', 'Tetraodontidae', 77, 82, 7.0, 8.0, 1.0, 'intermediate', 'aggressive', '["dwarf puffer","pea puffer fish","puffer"]'),
('Hemigrammus bleheri', 'Rummy Nose Tetra', 'freshwater_fish', 'Characidae', 75, 82, 5.5, 7.0, 2.0, 'intermediate', 'peaceful', '["rummy nose","firehead tetra"]'),
('Moenkhausia pittieri', 'Diamond Tetra', 'freshwater_fish', 'Characidae', 72, 80, 6.0, 7.5, 2.5, 'beginner', 'peaceful', '["diamond","pittieri"]'),
('Gymnocorymbus ternetzi', 'Black Skirt Tetra', 'freshwater_fish', 'Characidae', 68, 79, 6.5, 7.5, 3.0, 'beginner', 'semi_aggressive', '["black tetra","black widow tetra"]'),
('Tanichthys albonubes', 'White Cloud Mountain Minnow', 'freshwater_fish', 'Cyprinidae', 60, 72, 6.5, 7.5, 2.0, 'beginner', 'peaceful', '["white cloud","mountain minnow","WCMM"]'),
('Otocinclus vittatus', 'Otocinclus', 'freshwater_fish', 'Loricariidae', 72, 79, 6.5, 7.5, 2.0, 'beginner', 'peaceful', '["otto","oto catfish","dwarf suckerfish"]'),
('Crossocheilus oblongus', 'Siamese Algae Eater', 'freshwater_fish', 'Cyprinidae', 75, 79, 6.5, 7.5, 6.0, 'beginner', 'peaceful', '["SAE","algae eater"]'),
('Gyrinocheilus aymonieri', 'Chinese Algae Eater', 'freshwater_fish', 'Gyrinocheilidae', 77, 84, 6.5, 7.5, 10.0, 'beginner', 'semi_aggressive', '["CAE","algae eater"]'),
('Neolamprologus leleupi', 'Lemon Cichlid', 'freshwater_fish', 'Cichlidae', 76, 82, 7.5, 9.0, 4.0, 'intermediate', 'semi_aggressive', '["leleupi","tanganyika lemon"]'),
('Tropheus duboisi', 'White Spotted Cichlid', 'freshwater_fish', 'Cichlidae', 76, 82, 7.5, 9.0, 5.0, 'advanced', 'aggressive', '["duboisi","tropheus"]'),

-- SALTWATER FISH
('Amphiprion ocellaris', 'Ocellaris Clownfish', 'saltwater_fish', 'Pomacentridae', 75, 82, 8.1, 8.4, 4.5, 'beginner', 'semi_aggressive', '["clownfish","clown fish","nemo","false percula"]'),
('Amphiprion percula', 'True Percula Clownfish', 'saltwater_fish', 'Pomacentridae', 75, 82, 8.1, 8.4, 4.0, 'beginner', 'semi_aggressive', '["true perc","percula clownfish"]'),
('Premnas biaculeatus', 'Maroon Clownfish', 'saltwater_fish', 'Pomacentridae', 75, 82, 8.1, 8.4, 7.0, 'intermediate', 'aggressive', '["maroon clown","gold stripe maroon"]'),
('Paracanthurus hepatus', 'Blue Tang', 'saltwater_fish', 'Acanthuridae', 75, 82, 8.1, 8.4, 12.0, 'intermediate', 'semi_aggressive', '["hippo tang","regal tang","dory","pacific blue tang"]'),
('Zebrasoma flavescens', 'Yellow Tang', 'saltwater_fish', 'Acanthuridae', 75, 82, 8.1, 8.4, 8.0, 'beginner', 'semi_aggressive', '["yellow surgeonfish"]'),
('Chromis viridis', 'Blue-Green Chromis', 'saltwater_fish', 'Pomacentridae', 75, 82, 8.1, 8.4, 4.0, 'beginner', 'peaceful', '["green chromis","blue chromis"]'),
('Pterois volitans', 'Red Lionfish', 'saltwater_fish', 'Scorpaenidae', 72, 80, 8.1, 8.4, 15.0, 'intermediate', 'aggressive', '["lionfish","volitan lionfish"]'),
('Gramma loreto', 'Royal Gramma', 'saltwater_fish', 'Grammatidae', 74, 82, 8.1, 8.4, 3.5, 'beginner', 'semi_aggressive', '["fairy basslet","gramma"]'),
('Pseudocheilinus hexataenia', 'Sixline Wrasse', 'saltwater_fish', 'Labridae', 75, 82, 8.1, 8.4, 4.0, 'beginner', 'semi_aggressive', '["six line wrasse","sixline"]'),
('Labroides dimidiatus', 'Bluestreak Cleaner Wrasse', 'saltwater_fish', 'Labridae', 75, 82, 8.1, 8.4, 5.5, 'advanced', 'peaceful', '["cleaner wrasse"]'),
('Chrysiptera parasema', 'Yellowtail Damselfish', 'saltwater_fish', 'Pomacentridae', 75, 82, 8.1, 8.4, 3.5, 'beginner', 'semi_aggressive', '["yellowtail damsel","YT damsel"]'),
('Centropyge loricula', 'Flame Angelfish', 'saltwater_fish', 'Pomacanthidae', 75, 82, 8.1, 8.4, 4.0, 'intermediate', 'semi_aggressive', '["flame angel"]'),
('Centropyge bicolor', 'Bicolor Angelfish', 'saltwater_fish', 'Pomacanthidae', 75, 82, 8.1, 8.4, 5.0, 'advanced', 'semi_aggressive', '["bicolor angel"]'),
('Synchiropus splendidus', 'Mandarinfish', 'saltwater_fish', 'Callionymidae', 75, 82, 8.1, 8.4, 3.0, 'advanced', 'peaceful', '["mandarin fish","mandarin dragonet","psychedelic mandarin"]'),
('Gobiodon okinawae', 'Yellow Clown Goby', 'saltwater_fish', 'Gobiidae', 75, 82, 8.1, 8.4, 1.5, 'beginner', 'peaceful', '["clown goby","yellow goby"]'),
('Nemateleotris magnifica', 'Firefish', 'saltwater_fish', 'Gobiidae', 74, 82, 8.1, 8.4, 3.0, 'beginner', 'peaceful', '["fire goby","firefish goby"]'),
('Pterosynchiropus splendidus', 'Spotted Mandarin', 'saltwater_fish', 'Callionymidae', 75, 82, 8.1, 8.4, 3.0, 'advanced', 'peaceful', '["spotted mandarin dragonet"]'),

-- CORAL & FRAGS
('Acropora millepora', 'Millepora SPS Coral', 'coral_frags', 'Acroporidae', 76, 79, 8.1, 8.3, 12.0, 'advanced', 'semi_aggressive', '["millie","acro","SPS"]'),
('Euphyllia ancora', 'Hammer Coral', 'coral_frags', 'Euphylliidae', 74, 82, 8.1, 8.3, 10.0, 'intermediate', 'aggressive', '["hammer","anchor coral"]'),
('Euphyllia divisa', 'Frogspawn Coral', 'coral_frags', 'Euphylliidae', 74, 82, 8.1, 8.3, 10.0, 'intermediate', 'aggressive', '["frogspawn"]'),
('Euphyllia glabrescens', 'Torch Coral', 'coral_frags', 'Euphylliidae', 74, 82, 8.1, 8.3, 10.0, 'intermediate', 'aggressive', '["torch"]'),
('Blastomussa wellsi', 'Blastomussa', 'coral_frags', 'Mussidae', 74, 82, 8.1, 8.3, 8.0, 'beginner', 'peaceful', '["blasto","blastos"]'),
('Discosoma sp.', 'Mushroom Coral', 'coral_frags', 'Discosomatidae', 74, 82, 8.1, 8.3, 6.0, 'beginner', 'peaceful', '["mushrooms","shrooms","discosoma"]'),
('Zoanthus sp.', 'Zoanthids', 'coral_frags', 'Zoanthidae', 74, 82, 8.1, 8.3, 4.0, 'beginner', 'semi_aggressive', '["zoas","zoanthid frags","palys","palythoa"]'),
('Caulastrea furcata', 'Candy Cane Coral', 'coral_frags', 'Merulinidae', 74, 82, 8.1, 8.3, 8.0, 'beginner', 'peaceful', '["candy cane","candycane","trumpet coral"]'),
('Lobophyllia hemprichii', 'Lobophyllia', 'coral_frags', 'Lobophylliidae', 74, 82, 8.1, 8.3, 12.0, 'beginner', 'aggressive', '["lobo","open brain"]'),
('Trachyphyllia geoffroyi', 'Open Brain Coral', 'coral_frags', 'Lobophylliidae', 74, 82, 8.1, 8.3, 10.0, 'intermediate', 'semi_aggressive', '["open brain","trachyphyllia"]'),

-- INVERTEBRATES
('Neocaridina davidi', 'Red Cherry Shrimp', 'invertebrates', 'Atyidae', 68, 78, 6.5, 8.0, 1.5, 'beginner', 'peaceful', '["RCS","cherry shrimp","neocaridina shrimp"]'),
('Caridina cantonensis', 'Crystal Red Shrimp', 'invertebrates', 'Atyidae', 62, 74, 6.0, 7.0, 1.5, 'advanced', 'peaceful', '["CRS","crystal shrimp","bee shrimp"]'),
('Caridina multidentata', 'Amano Shrimp', 'invertebrates', 'Atyidae', 65, 78, 6.5, 7.5, 2.0, 'beginner', 'peaceful', '["amano","japonica shrimp","algae shrimp"]'),
('Nerite sp.', 'Nerite Snail', 'invertebrates', 'Neritidae', 65, 82, 7.0, 8.5, 1.0, 'beginner', 'peaceful', '["nerite","nerites","tiger nerite","olive nerite"]'),
('Pomacea bridgesii', 'Mystery Snail', 'invertebrates', 'Ampullariidae', 68, 80, 7.0, 8.0, 2.0, 'beginner', 'peaceful', '["mystery snail","spike topped apple snail"]'),
('Procambarus clarkii', 'Red Swamp Crayfish', 'invertebrates', 'Cambaridae', 65, 80, 7.0, 8.0, 5.0, 'intermediate', 'aggressive', '["red crayfish","crawfish","blue crayfish"]'),
('Lysmata amboinensis', 'Skunk Cleaner Shrimp', 'invertebrates', 'Lysmatidae', 75, 82, 8.1, 8.4, 2.5, 'beginner', 'peaceful', '["cleaner shrimp","skunk shrimp"]'),
('Lysmata wurdemanni', 'Peppermint Shrimp', 'invertebrates', 'Lysmatidae', 72, 82, 8.1, 8.4, 2.0, 'beginner', 'peaceful', '["peppermint","aiptasia eating shrimp"]'),
('Stenopus hispidus', 'Banded Coral Shrimp', 'invertebrates', 'Stenopodidae', 74, 82, 8.1, 8.4, 3.0, 'intermediate', 'aggressive', '["boxer shrimp","banded cleaner shrimp"]'),
('Linckia laevigata', 'Blue Linckia Starfish', 'invertebrates', 'Ophidiasteridae', 75, 82, 8.1, 8.4, 12.0, 'advanced', 'peaceful', '["blue star","linckia star"]'),
('Tridacna crocea', 'Crocea Clam', 'invertebrates', 'Tridacnidae', 76, 80, 8.1, 8.4, 6.0, 'advanced', 'peaceful', '["crocea","boring clam","giant clam"]'),

-- LIVE PLANTS
('Taxiphyllum barbieri', 'Java Moss', 'live_plants', 'Hypnaceae', 59, 86, 5.5, 8.0, null, 'beginner', 'peaceful', '["java moss","aquarium moss"]'),
('Microsorum pteropus', 'Java Fern', 'live_plants', 'Polypodiaceae', 68, 82, 6.0, 7.5, null, 'beginner', 'peaceful', '["java fern","fern"]'),
('Anubias barteri', 'Anubias', 'live_plants', 'Araceae', 68, 82, 6.0, 7.5, null, 'beginner', 'peaceful', '["anubias barteri","broad leaf anubias"]'),
('Anubias nana', 'Dwarf Anubias', 'live_plants', 'Araceae', 68, 82, 6.0, 7.5, null, 'beginner', 'peaceful', '["anubias nana","petite anubias"]'),
('Hygrophila polysperma', 'Dwarf Hygro', 'live_plants', 'Acanthaceae', 68, 82, 6.5, 7.5, null, 'beginner', 'peaceful', '["hygro","sunset hygro"]'),
('Vallisneria spiralis', 'Vallisneria', 'live_plants', 'Hydrocharitaceae', 60, 82, 6.5, 8.5, null, 'beginner', 'peaceful', '["vals","val","vallis","eel grass"]'),
('Ceratophyllum demersum', 'Hornwort', 'live_plants', 'Ceratophyllaceae', 59, 86, 6.0, 7.5, null, 'beginner', 'peaceful', '["hornwort","coontail"]'),
('Egeria densa', 'Brazilian Waterweed', 'live_plants', 'Hydrocharitaceae', 59, 77, 6.0, 8.0, null, 'beginner', 'peaceful', '["elodea","anacharis","waterweed"]'),
('Cryptocoryne wendtii', 'Wendtii Crypt', 'live_plants', 'Araceae', 72, 82, 6.0, 8.0, null, 'beginner', 'peaceful', '["crypt","cryptocoryne","wendtii"]'),
('Echinodorus grisebachii', 'Amazon Sword', 'live_plants', 'Alismataceae', 72, 82, 6.5, 7.5, null, 'beginner', 'peaceful', '["sword plant","amazon sword plant"]'),
('Ludwigia repens', 'Red Ludwigia', 'live_plants', 'Onagraceae', 68, 82, 5.5, 7.5, null, 'intermediate', 'peaceful', '["ludwigia","red plant"]'),
('Rotala rotundifolia', 'Rotala', 'live_plants', 'Lythraceae', 72, 82, 5.5, 7.5, null, 'intermediate', 'peaceful', '["rotala","pink rotala"]');
